name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.0.4
        ports:
          - 5000:27017-27019

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -f pom.xml test
